version: "3.5"
services:
  api1:
    container_name: api1
    build: api1/.
    volumes:
      - type: volume
        source: api1-logs
        target: /logs
    ports:
      - "8001:8001"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    depends_on:
      - cache
  api2:
    container_name: api2
    build: api2/.
    volumes:
      - type: volume
        source: api2-logs
        target: /logs
      - api2-logs:/logs
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    depends_on:
      - api1
  cache:
    container_name: redis1
    image: redis
    # command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 6379:6379
volumes:
  api1-logs:
  api2-logs:
