services:
  frontend:
    image: nginx:alpine
    container_name: frontend_server
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api1
      - api2
    networks:
      - app-network

  llm-app:  
    container_name: llm_app
    build:
      context: ./api1/llm  
      dockerfile: Dockerfile  # Use Dockerfile.gpu for GPU support
    ports:
      - "5050:5050" 
    volumes:
      - ./api1/llm/logs:/app/logs
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ./client/data-example:/app/data
    environment:
      - HF_HOME=/root/.cache/huggingface
      - MODEL_NAME=Qwen/Qwen3-0.6B
      - JSON_DATA_PATH=/app/data/movies.json
      - DEVICE_MAP=auto  # Options: 'auto', 'cpu', 'gpu'
      - TORCH_DTYPE=auto  # Options: 'auto', 'float16', 'float32', etc.
    networks:
      - app-network

  api1:
    container_name: api1_go
    build:
      context: ./api1
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - API2_URL=http://api2:8002
    volumes:
      - ./api1/logs:/app/logs
    networks:
      - app-network
    depends_on:
      - api2

  api2:
    container_name: api2_fastapi
    build: ./api2
    ports:
      - "8002:8002"
    volumes:
      - ./api2/logs:/app/logs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
