[tool.pytest.ini_options]
junit-xml = test_report.xml
testpaths = [
    "tests",
    "client",
]


addopts = [
    "--import-mode=importlib",
    "-rA",
    "--junit-xml=test_report.xml"

]
pythonpath = "."
